use_frameworks!

target 'DKDevKit_Example' do
  pod 'DKDevKit', :path => '../'

  target 'DKDevKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
